[tool.poetry]
name = "pyobs-alpaca"
version = "0.15.0-alpha.4"
description = "pyobs module for ASCOM Alpaca"
authors = ["Tim-Oliver Husser <thusser@uni-goettingen.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
requests = "^2.26"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
